package com.server.enums;

public enum Operation {

    CREATE_PRODUCT,
    READ_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,

    CREATE_EMPLOYEE,
    READ_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,

    GET_ALL_SUPPLIERS,
    GET_ALL_PRODUCTS,
    GET_ALL_EMPLOYEES,
    GET_ALL_DEPARTMENTS,

    GET_SUPPLIERS_BY_PRODUCT,
    LINK_SUPPLIER_PRODUCT,
    UNLINK_SUPPLIER_PRODUCT,

    LOGIN,
    REGISTER,
    DISCONNECT
}
